### ISSUE TITLE
Constructors erroneously collapsed in member function list

### ISSUE THREAD

**Issue by gennaroprota** [erez-o/docsforge#37] opened 2020-11-13 08:40 UTC
Hi,

I've noticed that, in class member function lists, DocsForge uses a single entry for all the constructors of the class. E.g.:

![DocsForge member list](https://user-images.githubusercontent.com/4961853/99045832-3768cc80-2592-11eb-9133-ff7043d9d950.png)

In this case, the documented class has both a default constructor and a deleted copy constructor, but DocsForge lists one constructor, and "reuses" the documentation of the deleted copy constructor for everything. This is instead the Doxygen output with my configuration:

![Doxygen member list](https://user-images.githubusercontent.com/4961853/99046722-751a2500-2593-11eb-91e3-2d3c979fe037.png)

Note, too, that the term "method" is usually frowned upon in C++ (whether with reason or not). The "correct" term is "member function".

**Comment by erez-o** [comment] 2020-11-13 10:45
Yes, it's currently by design, but let's think of a way it can be improved.

First of all, in the function page, all of overloads are displayed:

![Screenshot from 2020-11-13 12-17-51](https://user-images.githubusercontent.com/4282254/99061478-4a879680-25aa-11eb-8894-8fd6de678bbe.png)

So we're talking strictly about how overloads should be displayed as briefs on the class page.
 
There are 3 alternatives I can think of: 

1) The one I currently employ which is to display only one and take the first brief found on the file assuming it would be the most used case.

2) Display all of the overloads each at a different row, but notice that sometimes there can be even 10 overloads with all having pretty much the same documentation. Question is if it's not overcrowding the naive user looking at the class page to get a brief overview of the class. This approach will require a flag in the cfg because some may prefer and some won't, and even might want it ON for some classes, and OFF for others.  

3) A middle way approach - Note on the row that this method has overloads like : "+4 additional overloads" in the brief description table cell, so any user interested will click to see more. Maybe add a small icon at the corner of the function icon.

What do you think?

Note:
I personally think that doxygen class page is too crowded for the naive user (they don't split between class and function pages), that's why by design I'm not displaying on the class page for every function all the input parameters and the return value, opting for displaying the brief that doxygen displays only a few words.

About the note, docsforge supports other languages as well so I tried looking for a common denominator for now.

**Comment by gennaroprota** [comment] 2020-11-18 11:52
Thanks for the exhaustive reply. To be honest, I'm not sure what the best solution is. My gut feeling is that if the API is bloated (10 overloads of the same function), it's just normal for the documentation to be bloated as well. Making the docs _appear_ cleaner doesn't solve the underlying issue. Anyway, I'm fine with approach 3 as well. The case of constructors in C++ seems to be worth special handling, however, if that is possible. I find that having, say, the default constructor in the list, and then a link which says "+1 additional overload" to see the copy constructor is a bit strange :-) The special handling could consist in always showing copy and move constructors if they are declared for the class. Likewise for copy and move assignment operators. If that is even possible, of course, and if you agree.

**Comment by erez-o** [comment] 2020-11-18 14:42
Hmmm. I'm not sure constructors is necessarily a special case. 

I'll think I'll add both (2) and (3) to my TODO list, but (2) only as a simple ON/OFF for now.

**Comment by erez-o** [comment] 2020-11-22 17:32
The new version is live (3.4.20). 

![Screenshot from 2020-11-22 19-18-47](https://user-images.githubusercontent.com/4282254/99910588-95ff1a80-2cf7-11eb-8d3a-f1b408b303f2.png)

The following logic is now implemented:
1) "Overload" tag was added to any function with overloads (regardless if there's any brief description)
2) If multiple different (non empty) function briefs exist, display each on a separate row. If a This allows maintainers a simple way to not be overcrowded with too many function overloads - simply use the same brief.

Closing issue. If your original issue is not resolved, reopen.

**Closed as completed by erez-o** 2020-11-22 17:32 UTC
Labels: enhancement

**Comment by gennaroprota** [comment] 2020-11-25 11:28
Thank you so much! Just two nits: if you like that, too, could we change "Overload" to "overload", with a lowercase 'o'? (Or even "overloaded"; I don't have a strong opinion about that.) Secondly, in one case I now see that a private constructor appears among the overloads. Is there any option I can tweak to avoid that?

**Comment by erez-o** [comment] 2020-11-25 13:39
Can you please tell me the url + image of the private constructor that appears among the overloads?

**Comment by gennaroprota** [comment] 2020-11-25 14:03
Yes. You can see here that there's an "overload" marker:

  https://breath.docsforge.com/master/api/breath/last_api_error/

and overload #2, here:


https://breath.docsforge.com/master/api/breath/last_api_error/last_api_error/

is private. (I see that you asked for a URL+image, but I guess the URL is
enough. Please, tell me if you'd like a screenshot, as well.)

**Comment by gennaroprota** [comment] 2020-11-25 14:08
Yes. You can see here that there's an "overload" label:

  https://breath.docsforge.com/master/api/breath/last_api_error/

and overload (2), here:

  https://breath.docsforge.com/master/api/breath/last_api_error/last_api_error/

is private. (I see that you asked for a URL+image, but I guess the URL is enough. Please, tell me if you'd like a screenshot, as well.)

**Comment by erez-o** [comment] 2020-12-02 07:39
Fixed. Not yet released.

**Comment by erez-o** [comment] 2020-12-06 12:10
Released 3.4.21 , see https://breeze.docsforge.com/master/api/breeze/last_api_error/ and https://breeze.docsforge.com/master/api/breeze/last_api_error/last_api_error/
